AllCops:
  Exclude:
    - Gemfile
    - Rakefile
    - tmp/**/*
    - vendor/**/*
  TargetRubyVersion: 2.4

# Ruby 3.0 concern
Style/FrozenStringLiteralComment:
  Enabled: false

# double quotes preferred, except in require
Style/StringLiterals:
  Enabled: false
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# appropriate hash formatting varies wildly
Style/MultilineMethodCallBraceLayout:
  Enabled: false
Style/AlignHash:
  Enabled: false

# often aids readability
Style/RedundantSelf:
  Enabled: false
Style/ExtraSpacing:
  Enabled: false
Style/SpaceInsideBrackets:
  Enabled: false
Style/SpaceInsidePercentLiteralDelimiters:
  Enabled: false
Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false
Style/SpaceAfterColon:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/Alias:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false
Style/IndentAssignment:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false

# rarely aids readability
Style/EmptyLinesAroundBlockBody:
  Exclude: []
Style/AccessorMethodName:
  Exclude: []
Style/MultilineTernaryOperator:
  Exclude: []
Style/RescueModifier:
  Exclude: []

# {} distinguishes delimiters from method calls
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '{}'
    '%i': '{}'

# self-documentation preferred
Style/Documentation:
  Enabled: false

# conditionals should contain statements
Style/EmptyElse:
  EnforcedStyle: empty

# sufficient length for modern screens
Metrics/LineLength:
  Max: 120

# rare situations where readability is preferred over metrics aspirations
Metrics/ClassLength:
  Exclude: []
Metrics/MethodLength:
  Exclude: []
Metrics/AbcSize:
  Exclude: []
