language: ruby
services:
  - docker
env:
  global:
    - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
before_install:
  - gem update --system
  - gem --version
  - gem install trigger_build
script: bundle exec rake commit
after_success:
  - trigger_build MYOB-Technology http_stub_example_producer
cache: bundler
notifications:
  email:
    on_success: change
    on_failure: always
