language: ruby
services:
  - docker
before_install:
  - gem install trigger_build
after_success:
  - trigger_build MYOB-Technology http_stub_example_producer --org
cache: bundler
notifications:
  email:
    on_success: change
    on_failure: always
